### ISSUE TITLE
Feature Req: Exclude folder support

### ISSUE THREAD

**Issue by nabizi** [cicirello/generate-sitemap#113]
**Common pages are being added to sitemap**
I have a folder called common. The common folder includes html pages that included in many places in my website. The sitemap generator will include these files in the sitemap.xml but actually I don't want them to be included.

**Solution**
Add a config input param that takes a path of a folder. The script will then ignore these folders and not include any resource under it.

**Comment by cicirello** [comment]
@nabizi great idea. Thanks for submitting this issue.
