### ISSUE TITLE
generate-sitemap doesn't produce any output

### ISSUE THREAD

**Issue by t0rre** [cicirello/generate-sitemap#20]
As the title said, and I don't know why. I would be grateful if somebody could help me.
Here is my yml file:
```# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , christmas]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: generate-sitemap
      # You may pin to the exact commit or the version.
      # uses: cicirello/generate-sitemap@2777ea0908c8365591fe1f1960ef898ca326511b
        uses: cicirello/generate-sitemap@v1.6.1
        with:
          base-url-path: https://doktormugg.se/ # default is https://web.address.of.your.nifty.website/

 ```

**Comment by cicirello** [comment]
The generate-sitemap action doesn't actually commit or push the sitemap, so if that is your entire workflow you will need to add a step that does that.

Take a look at this workflow https://www.github.com/cicirello/cicirello.github.io/tree/master/.github%2Fworkflows%2Fsitemap-generation.yml and try the following. I have a step named output stats that simply outputs number of entries and location of sitemap. Add that step to your workflow to confirm it is generating something. Then you'll need to add a step to actually commit and push the sitemap. The same workflow that I linked to uses another action to do that (well it actually generates a pull request, but you could commit and push instead).

**Comment by t0rre** [comment]
Thanks! I got it working now. I don't know that much about actions, as you might have noticed.

**Comment by cicirello** [comment]
You're welcome. I'm happy to help.
