### ISSUE TITLE
Feature Req: [non UTF8 character error message console log]

### ISSUE THREAD

**Issue by TravisBrace** [cicirello/generate-sitemap#42]
**Is your feature request related to a problem? Please describe.**
If the sitemap finds a page with a non UTF8 encoded character it throws an error and exits

**Describe the solution you'd like**
Not sure what that would look like in python but would be a nice feature if before the script exited with the non UTF8 character error it logged what page it was finding the error on.

**Describe alternatives you've considered**
For anyone having a similar issue --

I cloned my project locally and grepped through the project to find the character with this command here 

`grep -raxv --include=*.html '.*' ./`

**Additional context**
Thanks for the awesome github action it's been much appreciated.

**Comment by cicirello** [comment]
@TravisBrace is the file that lead to the error in a public repository? If so can you link to it? It might be useful to investigate cause.

**Comment by TravisBrace** [comment]
@cicirello it's not currently but should be able to recreate an example. Will let you know

**Comment by cicirello** [comment]
@TravisBrace this is now fixed in v1.8.3, or if you are using the major version tag v1 the fix would be picked up as well. The issue was in the check if a noindex directive was present in an html file. I fixed it to just ignore non-utf8 characters while looking for the robots meta tag.
