### ISSUE TITLE
Regarding React App

### ISSUE THREAD

**Issue by sudip-mondal-2002** [cicirello/generate-sitemap#45]
Can I generate a sitemap during the production build using this and submit to my hosting service using GitHub actions?

**Comment by cicirello** [comment]
I'm not familiar with React so to answer your question I have a few questions:

1. Is React one of those frameworks where everything is generated with JS?
2. If so, is there a one to one relationship of source files to site urls?

**Comment by sudip-mondal-2002** [comment]
1. Yes React is a framework where everything is rendered with JS
2. So, we use React routers to map them, So we create one file or keep them in the entry file to the project.
3. Yes I think, the file I mentioned earlier should be parsed.

- Anyways there are some npm libraries those do the job in CLI, you might use them to create a GitHub action. Let me know if I could help further.

**Comment by cicirello** [comment]
It sounds beyond the scope of this particular action. It would probably be relatively straightforward though to create a new action to generate sitemaps for react apps using something like, https://www.npmjs.com/package/react-router-sitemap, as a basis for the action (or something similar).
