### ISSUE TITLE
BUG: [Doesn't exclude "noindex" files from sitemap]

### ISSUE THREAD

**Issue by BlenderTimer** [cicirello/generate-sitemap#86]
**Describe the bug**
The action doesn't seem to exclude html pages with the `<meta name="robots" content="noindex">` meta tag or set as "Disallow" in the robots.txt file. In my case this was my "404.html" file.

**To Reproduce**
1. Make sure you have a file (or files) that are set as "Disallow" in the robots.txt file or contain the `<meta name="robots" content="noindex">` meta tag in the page's html file.
2. Commit and push the repository.
3. Once the commit has finished, check the sitemap.xml file. You will see files included in the sitemap that should have been excluded.

**Expected behavior**
Should exclude any pages from the sitemap that contain the `<meta name="robots" content="noindex">` meta tag or are set as "Disallow" in the robots.txt file (such as my 404.html).

**Screenshots**
N/A

**Relevant System Info:**
 - OS: Linux Mint Debian Edition 4 (LMDE4)
 - Cinnamon Version: 5.0.7

**Additional context**
 - 404.html Link: [https://github.com/BlenderTimer/blendertimer.github.io/blob/main/404.html](https://github.com/BlenderTimer/blendertimer.github.io/blob/main/404.html) or [https://www.blendertimer.com/404.html](https://www.blendertimer.com/404.html)

**Comment by cicirello** [comment]
@BlenderTimer I just tried using your 404.html as a test case, and it was correctly excluded from the sitemap for me. So I took a closer look at your workflow, etc. Here's what I found, and how you can get things working.

1. It looks like you added the `<meta name="robots" content="noindex">` to your 404.html sometime after the last time your sitemap was generated by the action.
2. In a patch branch, you have a workflow step that should correctly handle committing and pushing the updated sitemap. See these lines in that patch branch: https://github.com/BlenderTimer/blendertimer.github.io/blob/1cdb4a23f3bff7acd05bec67645ff352252a3732/.github/workflows/generate-sitemap.yml#L39-L47 If you put those lines as the last step in the workflow in your main branch, it should comit and push correctly. GitHub Actions will always use the version of a workflow in your default branch, in this case main.
3. In your main branch workflow, it looks like you are trying to use generate-sitemap twice. The first one looks fine. The second one has inputs that don't exist. So just replace that with the step to commit and push from above.
4. The reason that the `Disallow: /404/` in your robots.txt isn't working is that `/404/` specifies a directory named 404. If you really want to use the robots.txt for that than `Disallow: /404.html` should work. But I'd recommend removing that line and allowing robots to crawl it. Your existing `<meta name="robots" content="noindex">` is enough to prevent it from being indexed, and is also enough to get generate-sitemap to exclude it from the sitemap.

**Comment by cicirello** [comment]
@BlenderTimer Your last step currently is the following:

```YAML
    - name: Update resources
      uses: cicirello/generate-sitemap@v1
      with:
        file-path: /sitemap.xml
        commit-msg: Update resources
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

The `uses: cicirello/generate-sitemap@v1` is attempting to run generate-sitemap a second time. If you inspect the logs of the workflow run, you'll see errors output by generate-sitemap because the inputs you have there `file-path`, `commit-msg`, and `github-token` are unknown to it.

The if statement in the step that I use for committing and pushing checks whether the sitemap has changed relative to what is in the branch, and only tries to commit and push if it is different.

**Comment by BlenderTimer** [comment]
But if I don't use `Update resources` I have to manually merge a pull request every time I commit (and the sitemap is different). Although that method seems to fix the problem of including `noindex` files. How to I make it so that it merges automatically?

**Comment by cicirello** [comment]
The `name: Update resources` is just a name you gave to that step. That step is actually not currently doing anything, as it is (see messages at bottom of workflow run on the actions tab). I just sent you a PR with a step that should work.

**Comment by BlenderTimer** [comment]
Ah, I see. (I'm not a GitHub expert lol) I merged your PR and it looks like everything is working now!
Thank you so much!

**Comment by cicirello** [comment]
You're welcome.
